import { ExampleReference } from "@/types";

export const EXAMPLE_LIBRARY: ExampleReference[] = [
  {
    id: "saas-hero-professional",
    industry: "saas",
    sectionType: "hero",
    designStyle: "professional",
    tags: ["dashboard", "b2b", "clarity", "cta"],
    description: "Professional SaaS hero with a strong headline, supporting copy, and balanced product card.",
    html: `<section id="hero" data-block-id="hero" class="bg-slate-950 text-white pt-24 pb-20"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><span class="inline-flex rounded-full border border-cyan-400/20 bg-cyan-400/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-200">B2B SaaS</span><h1 class="mt-6 text-5xl font-semibold tracking-tight">Close the pipeline with a landing page built for clarity.</h1><p class="mt-5 max-w-xl text-lg leading-8 text-slate-300">Explain the offer, back it with proof, and guide the visitor to a single next step.</p></div><div class="rounded-[28px] border border-white/10 bg-white/5 p-6"></div></div></div></section>`,
  },
  {
    id: "saas-features-professional",
    industry: "saas",
    sectionType: "features",
    designStyle: "professional",
    tags: ["grid", "cards", "product"],
    description: "Clean feature grid with concise card copy.",
    html: `<section id="features" data-block-id="features" class="bg-white py-20 text-slate-900"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="max-w-2xl"><h2 class="text-4xl font-semibold tracking-tight">What teams get on day one.</h2><p class="mt-4 text-base leading-7 text-slate-600">Every section is designed to stay scannable and conversion-focused.</p></div><div class="mt-12 grid gap-5 lg:grid-cols-3"></div></div></section>`,
  },
  {
    id: "agency-hero-elegant",
    industry: "agency",
    sectionType: "hero",
    designStyle: "elegant",
    tags: ["luxury", "studio", "services"],
    description: "Elegant agency hero with restrained palette and editorial spacing.",
    html: `<section id="hero" data-block-id="hero" class="bg-[#111827] py-24 text-white"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="grid gap-10 lg:grid-cols-2 lg:items-center"><div><p class="text-sm uppercase tracking-[0.3em] text-amber-300">Studio Strategy</p><h1 class="mt-6 text-5xl font-semibold tracking-tight">Position premium services without sounding generic.</h1><p class="mt-5 max-w-xl text-lg leading-8 text-slate-300">Use proof, pacing, and an intentional section rhythm to create confidence.</p></div></div></div></section>`,
  },
  {
    id: "agency-proof-elegant",
    industry: "agency",
    sectionType: "social-proof",
    designStyle: "elegant",
    tags: ["metrics", "credibility", "results"],
    description: "Elegant proof section with metrics and outcomes.",
    html: `<section id="social-proof" data-block-id="social-proof" class="bg-[#f7f2ea] py-16 text-slate-900"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="grid gap-5 md:grid-cols-3"></div></div></section>`,
  },
  {
    id: "course-hero-playful",
    industry: "education",
    sectionType: "hero",
    designStyle: "playful",
    tags: ["course", "community", "creator"],
    description: "Playful course hero with energetic gradients and creator framing.",
    html: `<section id="hero" data-block-id="hero" class="bg-gradient-to-br from-fuchsia-500 via-orange-400 to-amber-300 py-24 text-slate-950"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="max-w-3xl"><p class="text-sm font-semibold uppercase tracking-[0.24em] text-fuchsia-950/70">Creator-led cohort</p><h1 class="mt-6 text-5xl font-semibold tracking-tight">Launch a page that feels as alive as the product behind it.</h1></div></div></section>`,
  },
  {
    id: "course-cta-playful",
    industry: "education",
    sectionType: "cta",
    designStyle: "playful",
    tags: ["cta", "signup", "energy"],
    description: "High-energy CTA block with bright contrast.",
    html: `<section id="cta" data-block-id="cta" class="bg-fuchsia-600 py-16 text-white"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="rounded-[28px] bg-slate-950 px-8 py-10"></div></div></section>`,
  },
  {
    id: "local-services-minimal",
    industry: "local-services",
    sectionType: "features",
    designStyle: "minimal",
    tags: ["trust", "services", "simple"],
    description: "Minimal service section with straightforward cards and clean spacing.",
    html: `<section id="features" data-block-id="features" class="bg-white py-20 text-black"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3"></div></div></section>`,
  },
  {
    id: "generic-pricing-bold",
    industry: "saas",
    sectionType: "pricing",
    designStyle: "bold",
    tags: ["pricing", "dark", "contrast"],
    description: "Dark pricing table with strong contrast and highlighted offer.",
    html: `<section id="pricing" data-block-id="pricing" class="bg-black py-20 text-white"><div class="max-w-[1100px] mx-auto px-4 sm:px-6 lg:px-8"><div class="grid gap-5 lg:grid-cols-3"></div></div></section>`,
  },
];
